### ISSUE TITLE
Laravel v10

### ISSUE THREAD

**Issue by agentsquidflaps** [gghughunishvili/entrust#15]
Hi,

I was wondering if there were any plans to add a tagged release for the Laravel 10 compatibility changes you've made. 

At present, the only way to get this to work with Laravel 10 is to set composer to "gghughunishvili/entrust": "dev-master" (or similar), which isn't ideal. It would be preferable to use a specific version, if possible!

Thanks in advance!

**Comment by agentsquidflaps** [comment]
Hi again, 

Politely asking, has there's been any development on this one?

Thanks in advance!

**Comment by gghughunishvili** [comment]
Hi, It’s not released yet but I will prioritize it this week.

**Comment by gghughunishvili** [comment]
Added version 10.0.0 and it should be fine to install it now. Thanks.

**Comment by agentsquidflaps** [comment]
Thank you so much! :heart:
