### ISSUE TITLE
Laravel 7

### ISSUE THREAD

**Issue by C0kkie** [gghughunishvili/entrust#3]
Hello,

can you PLEASE add support for laravel 7?

**Comment by C0kkie** [comment]
I've added a PR, this should support laravel 7 probably

**Comment by gghughunishvili** [comment]
Hello @C0kkie, thanks for opening up the ticket. I will have a look and let you know if those changes are enough and will update the package by EOD.

**Comment by C0kkie** [comment]
Thanks, i would appreciate it if you can look into it asap

**Comment by C0kkie** [comment]
Also what means EOD? :D

**Comment by gghughunishvili** [comment]
EOD = End of Day. 

I am at work at this moment and will have a look once I am done, approximately 6 hours or in 3 hours during break time if it is quick.

**Comment by C0kkie** [comment]
Ah alright

**Comment by gghughunishvili** [comment]
@C0kkie I've just checked the latest version of this package on Laravel 7 and it works quite well, would you mind to write or get a screenshot what error you are encountering? Thanks.

**Comment by C0kkie** [comment]
The problem is that if i run composer update i get error message that entrust isnt compatible at the moment

**Comment by C0kkie** [comment]
- gghughunishvili/entrust 2.1.0 requires illuminate/support ~6.0 -> satisfiable by laravel/framework[v6.18.0], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].

**Comment by gghughunishvili** [comment]
@C0kkie Thanks for the PR. Merged it and tagged as version 3.0.0 https://github.com/gghughunishvili/entrust/releases/tag/3.0.0.

> Closing this issue.

**Comment by C0kkie** [comment]
Alright it works :)
