### ISSUE TITLE
Upgrade to laravel 8 - possible solution

### ISSUE THREAD

**Issue by gghughunishvili** [gghughunishvili/entrust#7]
Changes suggested by @C0kkie

**Comment by gghughunishvili** [comment]
https://github.com/gghughunishvili/entrust/pull/8

**Comment by C0kkie** [comment]
thanks

**Comment by gghughunishvili** [comment]
> thanks

Now in order to install it, you have to run the following command:
```
composer require gghughunishvili/entrust:dev-rc4
```

**Comment by C0kkie** [comment]
Installed without a error
