### ISSUE TITLE
Laravel 8 support?

### ISSUE THREAD

**Issue by VictorPulzz** [gghughunishvili/entrust#9]
It would be cool if you add support for laravel 8 :)

**Comment by gghughunishvili** [comment]
@VictorPullzz I'm pretty busy now. For a temporary solution, you could use RC which supports Laravel 8.

```
composer require gghughunishvili/entrust:dev-rc4
```

**Comment by Levivb** [comment]
Reposting here since this issue is still open

rc-4 seems to be working for us no problem. A stable tag should be okay :)

also see https://github.com/gghughunishvili/entrust/pull/6

**Comment by Levivb** [comment]
bump :)

**Comment by gghughunishvili** [comment]
Updated to V `4.0.0`.
